scipp/sciline

- src/sciline/domain.py
- src/sciline/pipeline.py
- tests/complex_workflow_test.py
- tests/domain_test.py
- tests/pipeline_test.py
This changes `Scope` to take the aliased type as a second parameter. This is required for detecting more issues via `mypy`.
I could not find a way of automatically also inheriting from this class, so now we have to specify this twice. In practice we may often reuse the same `Scope` subclass many times (see `ArrayT` example test), so this is hopefully not too much overhead.
> Better parametrized domain type

- src/sciline/visualize.py
- tests/visualize_test.py
This was probably broken by unrelated changes to how the graph was stored.
> Fix duplicate display of generic params in visualize()

- docs/developer/architecture-and-design/index.md
- docs/developer/architecture-and-design/workflow-design.md
- docs/developer/index.md
> Add architecture design document

- src/sciline/param_table.py
- src/sciline/series.py
This uses the string representation for the html_repr column names in the case where `.__name__` is not defined.
This is the case for `python<3.10`.
One slightly annoying thing is that when you have a parameter defined as `Filename[Sample]`, in py310 the column header will be `Filename`, while in py39 it becomes `Filename[Sample]`.
I could not use the string repr (with module name stripped) for all cases, because when you have a type defined simply as `Filename = NewType('Filename', str)`, then the column name becomes something like `new_type at 0x7f48681074c0>`. In this case it is better to use the `.__name__`.
So we use the name when we can, and the string repr when `.__name__` is not available.
Fixes #38
> Use str repr for param table html repr when `__name__` does not exist

- src/sciline/pipeline.py
- src/sciline/scheduler.py
- src/sciline/task_graph.py
- tests/pipeline_test.py
- tests/task_graph_test.py
> ``compute`` returns ``dict`` instead of ``tuple``.

- src/sciline/__init__.py
- src/sciline/pipeline.py
- tests/pipeline_test.py
> Add Pipeline.bind_and_call

- src/sciline/pipeline.py
- tests/complex_workflow_test.py
- tests/pipeline_with_optional_test.py
- tests/pipeline_with_param_table_test.py
Fixes #40.
Should we add top-level docs for this?
> Better handling of `typing.Optional`

- src/sciline/pipeline.py
- src/sciline/typing.py
- src/sciline/visualize.py
- tests/visualize_test.py
Without this, graphs that make heavy use of generics are pretty unreadable. It is enabled by default.
> Cluster generic products when visualizing graph

- src/sciline/pipeline.py
- tests/pipeline_test.py
Fixes #47
It seems to be very difficult to appease mypy here because type guards (`_is_multiple_keys`) only apply in the then-branch, not the else-branch. So I just disabled the affected checks.
> Support iterables in pipeline.get

- src/sciline/visualize.py
Currently the text in the rendered task graphs is not selectable.
The reason is that they are rendered into `<img>` tags instead of into `<svg>`.
This change makes them render as a `svg` in Jupyter notebooks and this allows the user to select names of nodes and edges.
This also enables interesting future features such as tool-tips on hover for quickly getting an idea of what a particular node in the graph does.
> fix: make names in the graph selectable in jupyter

- src/sciline/pipeline.py
- tests/pipeline_test.py
Fixes #69 
A type tuple `a` is considered more "special" than a type tuple `b` if the number of `TypeVar`s in `a` is lower than in `b`.
> feat: prioritize specialized providers over generic

- src/sciline/__init__.py
- src/sciline/handler.py
- src/sciline/pipeline.py
- src/sciline/visualize.py
- tests/pipeline_test.py
- tests/pipeline_with_param_table_test.py
- tests/task_graph_test.py
- tests/visualize_test.py
Fixes #79.
This avoids wasting a lot of time when working with scientists to draft a workflow. Previously I had to add a ton of dummy providers. I think this may also be helpful later to highlight which parameters still need to be set.
Currently this only works for the non-param-table case, we can add support for that later.
Example:
> Allow visualization of graphs with missing requirements

- src/sciline/pipeline.py
This helps to debug pipelines when you get the error message `Multiple providers found for type XXX`, but you don't know which are the providers that are overlapping.
> Print the matching providers as part of the error message

- src/sciline/pipeline.py
- tests/pipeline_test.py
- tests/pipeline_with_param_table_test.py
> Support replacing params and providers

- .copier-answers.yml
- LICENSE
- docs/conf.py
- requirements/base.txt
- requirements/basetest.txt
- requirements/dev.txt
- requirements/docs.txt
- requirements/mypy.txt
- requirements/test-dask.txt
- requirements/wheels.txt
- src/sciline/__init__.py
- tests/package_test.py
- tox.ini
Ran `copier update` and `tox -e deps` with no other changes. This should fixed the failing "unpinned" pipeline (which was missing NumPy when running tests).
> copier update & fix unpinned nightly

- src/sciline/pipeline.py
- tests/pipeline_test.py
- tests/pipeline_with_param_table_test.py
This makes it possible to make a copy of an existing pipeline.
One can then, for example modify the parameters of the new pipeline.
> Add pipeline copy method

- src/sciline/display.py
- src/sciline/pipeline.py
- src/sciline/utils.py
- tests/pipeline_test.py
- tests/pipeline_with_param_table_test.py
> Html repr for pipeline

- src/sciline/display.py
- src/sciline/pipeline.py
- src/sciline/scheduler.py
- src/sciline/task_graph.py
- src/sciline/typing.py
- src/sciline/utils.py
> feat: task graph html repr

- src/sciline/pipeline.py
- tests/pipeline_test.py
> Add kwargs to `.compute()`

- docs/user-guide/parameter-tables.ipynb
- src/sciline/param_table.py
- src/sciline/pipeline.py
- tests/param_table_test.py
- tests/pipeline_with_optional_test.py
- tests/pipeline_with_param_table_test.py
Fixes #58.
Also fixes #105. We support replacing tables, but each table is treated atomically, i.e., we do not support replacing a column in an existing table when adding another table.
> Support param tables with only index and no columns

- docs/index.md
> Docs: Add links to examples, mention dask

- docs/api-reference/index.md
- src/sciline/sphinxext/__init__.py
- src/sciline/sphinxext/domain_types.py
Fixes #61
This turns the formatter from https://github.com/scipp/copier_template/pull/124 into a sphinx extension. I am going to add code to use it to the copier template.
> Add domain_types sphinx extension

- src/sciline/visualize.py
Fixes #104 
Here's how the graph looks after the change:
I'm still a bit unsure what the correct behavior is here.
When should two `Series[ ... ]` nodes be collected in a subgraph?
Is it when *all* types inside `[ ... ]` are the same?
> fix: separate series subgraphs by index name

- src/sciline/__init__.py
- src/sciline/_provider.py
- src/sciline/display.py
- src/sciline/handler.py
- src/sciline/pipeline.py
- src/sciline/scheduler.py
- src/sciline/task_graph.py
- src/sciline/typing.py
- src/sciline/utils.py
- src/sciline/visualize.py
- tests/conftest.py
- tests/dask_scheduler_test.py
- tests/pipeline_test.py
- tests/pipeline_with_optional_test.py
- tests/pipeline_with_param_table_test.py
> Support keyword-only arguments

- src/sciline/_provider.py
- tests/pipeline_test.py
> Detect missing typehint early

- src/sciline/pipeline.py
- src/sciline/task_graph.py
- tests/task_graph_test.py
Needed by https://github.com/scipp/essreflectometry/issues/6
I went with `TaskGraph.keys` instead of `TaskGraph.nodes` in order to avoid the discussion of whether data and provider nodes are conceptually separate or the same node, see #124.
> Add TaskGraph.keys

- src/sciline/sphinxext/domain_types.py
> Fix type name parsing in sphinx extension.

- tests/_provider_test.py
Maybe we could have have some direct/independent tests on ``ArgSpec``.
> More tests on ArgSpec

- docs/recipes/applying-decorators.ipynb
- docs/recipes/index.md
- src/sciline/_provider.py
- tests/_provider_test.py
- tests/pipeline_test.py
> Support decorated providers (again)

- src/sciline/_provider.py
- tests/_provider_test.py
- tests/pipeline_test.py
> Support most callables

- src/sciline/visualize.py
Make sure we still have clusters in the visualization when using generics.
Fixes #151
> Fix blue cluster boxes in task graph visualization

- docs/developer/adr/0002-remove-special-handling-of-optional-and-union.md
> Propose ADR 0002: Remove special handling of Optional and Union

- src/sciline/_provider.py
- src/sciline/pipeline.py
- tests/pipeline_with_optional_test.py
- tests/utils_test.py
While `Pipeline` will be re-implemented, I nevertheless made this change, since it allows for updating units tests with new expected behavior, which will make the re-implementation easier/smaller (will pass the same unit tests), decoupling the behavior change from the re-implementation.
> Implement ADR 0002 (remove special handling of Optional and Union)

- src/sciline/data_graph.py
- src/sciline/pipeline.py
- tests/pipeline_map_reduce_test.py
This will be required for a variety of functionality that we plan to add in Sciline or elsewhere. A simple example is #83:
```python
import networkx as nx
import pandas as pd
g = workflow.networkx_graph
nodes = [node for node in g.nodes() if len(g.in_edges(node)) == 0]
nodes = [node for node in nodes if 'provider' not in g.nodes[node]]
not_set = '(not set)'
df = pd.DataFrame(
{'node': nodes, 'value': [g.nodes[node].get('value', not_set) for node in nodes]}
)
df
```
I don't know if this (without the Pandas bit) is something that should be added as a helper function in Sciline, or more specifically in our applications, e.g., in ESSreduce?
> Expose and rename properties for accessing underlying graphs and indices

- src/sciline/pipeline.py
- tests/pipeline_map_reduce_test.py
Previously the implementation was using the index names of the graph instead of the node. If the node had, e.g., 1 index but resulted from a reduction of a second index we previously got an exception.
> Fix exception in compute_mapped for partially reducing pipelines

- src/sciline/_provider.py
- src/sciline/data_graph.py
- src/sciline/visualize.py
- tests/pipeline_setitem_test.py
Fixes #176
I am not 100% confident that checking the function is enough because `arg_spec` gets overwritten when generic providers are specialised. However, I did not manage to find a case where this lead to a wrong result in `Pipeline.__setitem__`.
> Add Provider.__eq__

- src/sciline/pipeline.py
- tests/pipeline_test.py
- tests/visualize_test.py
> feat: add method to list leaf nodes

- src/sciline/pipeline.py
- src/sciline/task_graph.py
- src/sciline/visualize.py
Here is an before and after for ESSsans' `IofQ[SampleRun]`.
Before:
After:
Fixes #82.
> Add `mode` argument to `visualize` for more compact data or task graph display

- docs/api-reference/index.md
- pyproject.toml
- src/sciline/__init__.py
- src/sciline/pipeline.py
- src/sciline/reporter.py
- src/sciline/scheduler.py
- src/sciline/task_graph.py
- tests/reporter_test.py
This PR adds tools for showing the progress of a `Pipeline.compute` call. For now, I only implemented support for rich. But other libraries like tqdm could be added.
See also #26 which suggests to stick with Dask's own tools, in particular in Jupyter. I decided to go with this implementation because the BIFROST workflow already has a progress bar and I don't want to lose it when refactoring to use Sciline more. The BIFROST workflow currently takes ~10min and I think it is important to show that it is making progress. And it makes sense to run such a long process in a terminal outside of a Jupyter notebook for analysis.
The `Reporter` interface proposed here is flexible enough to support other kinds of reporting such as timing providers.
> Add progress reporters

- docs/recipes/replacing-providers.ipynb
Adding an example in the docs for adding a custom step in a pipeline when we don't have access to the original pipeline or providers code.
> Add an example of inserting a custom step in a pipeline

- src/sciline/pipeline.py
Fixes #196 
For now, this just makes the error more explicit. Implementing the affected functions without Pandas is complicated and not worthwhile at this point. We can revisit if this turn out to be a problem for more people.
> Clearer error messages if Pandas is missing

- src/sciline/domain.py
We should make a release with the new feature first and then deprecate. This will make transition easier. See, e.g., https://github.com/scipp/essreduce/pull/227.
> Do not deprecate ScopeTwoParams

- src/sciline/domain.py
We have a new release that includes variadic `Scope` without deprecating `ScopeTwoParams`. So downstream packages have a chance to update. So we can now deprecate `ScopeTwoParams` for real. We should just wait a bit before making another release.
Related: #205,#208
> Deprecate ScopeTwoParams

- src/sciline/pipeline.py
- tests/pipeline_test.py
This avoids printing possibly hundreds of types. I think the old implementation was mainly meant for case 2 below, but case 1 feels more common in practice. We now print ~a little "tree"~ the path from the missing node to the target node, e.g.,:
```
UnsatisfiedRequirement: Missing input node 'Filename'. Affects requested targets (via providers given in parentheses):
1. Filename → (__main__.load) → RawData → (__main__.clean) → CleanedData → (__main__.process) → Result
```
Try it out, e.g., with the "Getting Started" notebook:
Case 1: Remove the `Filename` param and try to compute `Result`
Case 2: Try to compute something not in the graph, such as `int`
> Print path to target when input node is missing

- src/sciline/data_graph.py
- tests/pipeline_test.py
This amends the changes of #212 to allow passing an empty list of constraints when creating a pipeline:
```python
sciline.Pipeline([...], constraints={T: []})
```
This effectively removes all occurrences of `T` from the graph. This can be useful, e.g., with the `GenericNexusWorkflow` when we don't need any monitors. Then we can set `monitor_types=[]` instead of having to specify an arbitrary monitor type that may not even exist at the instrument.
> Allow constraining typevars to empty set
